### ISSUE TITLE
清理工作应该不需要停掉Kubernetes机群

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/heapster#4]
README.md中：

> 删除 Heapster, InfluxDB, Grafana
> 
> core@zodiac-01 ~/liuqs $ ./kube.sh stop
> heapster pods have been removed.

`./kube.sh stop`是把整个机群都停了？

我看这个例子 https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md 貌似可以其几个pod？

**Comment by pineking** [comment]
stop 不会对集群造成影响，只是把对集群的监控删掉，具体是删除heapster和influxdb-grafana两个pod

后面的问题没看懂， ./kube.sh start 其实就是调用这个例子 https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md 中的kubectl create -f deploy/kube-config/influxdb/的命令，两者操作是一致的，./kube.sh start 也是创建heapster和influxdb-grafana两个pods和相应的services。

**Comment by wangkuiyi** [comment]
我理解了。这里的 `./kube.sh` 不是 Kubernetes 的脚本，而是 heapster 里的脚本。之前提issue是误会了。
